version: '3.8'

services:
  mongo-producao:
    image: mongo:6
    container_name: fastfood-producao-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - fastfood-producao-mongo:/data/db
    networks:
      - fastfood-network

  app-producao:
    build: .
    container_name: fastfood-producao-app
    depends_on:
      - mongo-producao
    ports:
      - "8082:8082"
      - "5007:5005"
    command: >
      java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
           -jar app.jar
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-producao:27017/fastfood-producao
    networks:
      - fastfood-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

volumes:
  fastfood-producao-mongo:

networks:
  fastfood-network:
    external: true
