version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: fastfood-producao-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - fastfood-mongo:/data/db
    networks:
      - fastfood-net

  app:
    build: .
    container_name: fastfood-producao-app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/fastfood-producao
    networks:
      - fastfood-net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

volumes:
  fastfood-mongo:

networks:
  fastfood-net:
