server:
  servlet:
    context-path: /fastfood-producao
  port: 8082
  error:
    include-message: always
    include-stacktrace: always

spring:
  data:
    mongodb:
      uri: mongodb://mongo-producao:27017/fastfood-producao

security:
  jwt:
    secret: ${JWT_SECRET:change_this_in_prod}
    expiration: ${JWT_EXPIRATION:3600} # segundos
    algorithm: HS256

external:
  auth-api:
    url: https://y8vlcu477a.execute-api.us-east-1.amazonaws.com/gerar-token
    validar-token-url: https://y8vlcu477a.execute-api.us-east-1.amazonaws.com/validar-token

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,liveness,readiness
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true
