apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-fastfood
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fast-food
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80