apiVersion: v1
data:
  POSTGRES_DB: ZmFzdGZvb2Q=
  POSTGRES_PASSWORD: ZmFzdGZvb2QxMjM=
  POSTGRES_USER: ZmFzdGZvb2RfYWRtaW4=
  URL: amRiYzpwb3N0Z3Jlc3FsOi8vZmFzdGZvb2QtZGIuY2RwNWpveHEzc2poLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2Zhc3Rmb29k
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-secret