apiVersion: v1
kind: Service
metadata:
  name: svc-fastfood
  labels:
    app: svc-fastfood
spec:
  selector:
    app: fast-food
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort
  